const drugs = [
   {
     "drugid": 1,
     "genericname": "Bendamustine Hydrochloride",
     "brandname": "Bendeka",
     "companyname": "Cephalon",
     "indication": "Cancer",
     "price": "$2,473.80",
     "medicared": "$2,102,477",
     "medicareb": "$233,169,546",
     "medicaid": "$22,573,710",
     "federal": "$257,845,733",
     "publicinstitution": "Institute for Microbiology and Experimental Therapy"
   },
   {
     "drugid": 2,
     "genericname": "Methylnaltrexone Bromide",
     "brandname": "RELISTOR",
     "companyname": "Salix",
     "indication": "Irritable Bowel Syndrome",
     "price": "$124.66",
     "medicared": "",
     "medicareb": "",
     "medicaid": "$11,255,296",
     "federal": "$11,255,296",
     "publicinstitution": "University of Chicago"
   },
   {
     "drugid": 3,
     "genericname": "Gadoxetate Disodium",
     "brandname": "Eovist",
     "companyname": "Bayer",
     "indication": "",
     "price": "$141.96",
     "medicared": "",
     "medicareb": "$985,022",
     "medicaid": "$132,577",
     "federal": "$1,117,599",
     "publicinstitution": "Massachusets General Hospital "
   },
   {
     "drugid": 4,
     "genericname": "Lobenguane Sulfate",
     "brandname": "",
     "companyname": "GE",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of Michigan "
   },
   {
     "drugid": 5,
     "genericname": "Lacosamide",
     "brandname": "Vimpat",
     "companyname": "UCB",
     "indication": "Seizures",
     "price": "$943.11",
     "medicared": "$545,362,956",
     "medicareb": "",
     "medicaid": "$356,847,175",
     "federal": "$902,210,131",
     "publicinstitution": "Univeristy of Houston/Research Corporation Tech"
   },
   {
     "drugid": 6,
     "genericname": "Plerixafor",
     "brandname": "Mozobil",
     "companyname": "Genzyme",
     "indication": "",
     "price": "$8,425.76",
     "medicared": "$4,422,846",
     "medicareb": "$19,707,513",
     "medicaid": "$4,030,405",
     "federal": "$28,160,764",
     "publicinstitution": "Rega Institute for Medical Research"
   },
   {
     "drugid": 7,
     "genericname": "Gadofosveset Trisodium",
     "brandname": "Vasovist",
     "companyname": "Lantheus ",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Massachusetts General Hospital "
   },
   {
     "drugid": 8,
     "genericname": "Artemether, lumefantrine",
     "brandname": "Coartem",
     "companyname": "Novartis",
     "indication": "Malaria",
     "price": "$122.63",
     "medicared": "$97,342",
     "medicareb": "",
     "medicaid": "$28,270",
     "federal": "$125,612",
     "publicinstitution": "Institute of Microbiology and Epidemology "
   },
   {
     "drugid": 9,
     "genericname": "Pralatrexate",
     "brandname": "Folotyn",
     "companyname": "Allos",
     "indication": "Cancer",
     "price": "$5,770.87",
     "medicared": "$981,871",
     "medicareb": "$17,107,437",
     "medicaid": "$866,871",
     "federal": "$18,956,179",
     "publicinstitution": "Sloan-Kettering for Cancer Research, SRI International"
   },
   {
     "drugid": 10,
     "genericname": "Romidepsin",
     "brandname": "Istodax",
     "companyname": "Celgene",
     "indication": "Cancer",
     "price": "$3,198.65",
     "medicared": "$506,966",
     "medicareb": "$32,077,997",
     "medicaid": "$2,928,845",
     "federal": "$35,513,808",
     "publicinstitution": "Harvard Univeristy/University of Tokyo"
   },
   {
     "drugid": 11,
     "genericname": "Capsaicin",
     "brandname": "",
     "companyname": "Acorda",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of California "
   },
   {
     "drugid": 12,
     "genericname": "Fampridine",
     "brandname": "Ampyra",
     "companyname": "Acorda",
     "indication": "MS",
     "price": "$2,934.14",
     "medicared": "$282,304,089",
     "medicareb": "",
     "medicaid": "",
     "federal": "$282,304,089",
     "publicinstitution": "Purdue University "
   },
   {
     "drugid": 13,
     "genericname": "Ulipristal Acetate",
     "brandname": "Ella",
     "companyname": "Lab HRA",
     "indication": "",
     "price": "$35.75",
     "medicared": "$21,367",
     "medicareb": "",
     "medicaid": "$1,160,264",
     "federal": "$1,181,631",
     "publicinstitution": "HHS/Research Triangle Institute "
   },
   {
     "drugid": 14,
     "genericname": "Eribulin Mesylate",
     "brandname": "Halaven",
     "companyname": "Eisai",
     "indication": "Cancer",
     "price": "$1,180",
     "medicared": "$906,346",
     "medicareb": "$51,908,493",
     "medicaid": "",
     "federal": "$52,814,839",
     "publicinstitution": "Harvard Univeristy/NCl"
   },
   {
     "drugid": 15,
     "genericname": "Abiraterone Acetate",
     "brandname": "Zytiga",
     "companyname": "Janssen",
     "indication": "Cancer",
     "price": "",
     "medicared": "$1,475,649,551",
     "medicareb": "",
     "medicaid": "$83,846,549",
     "federal": "$1,559,496,100",
     "publicinstitution": "Institute of Cancer Research (UK)/Univeristy of London"
   },
   {
     "drugid": 16,
     "genericname": "Linagliptin",
     "brandname": "Tradjenta",
     "companyname": "Boehringer",
     "indication": "Diabetes",
     "price": "$462.34",
     "medicared": "$1,043,195,403",
     "medicareb": "",
     "medicaid": "$136,100,254",
     "federal": "$1,179,295,657",
     "publicinstitution": "Univeristy of Toronto/Tufts College/NE Medical Center"
   },
   {
     "drugid": 17,
     "genericname": "Deferiprone",
     "brandname": "Ferriprox",
     "companyname": "Apopharma",
     "indication": "",
     "price": "$6,363.07",
     "medicared": "$21,276,965",
     "medicareb": "",
     "medicaid": "$21,128,283",
     "federal": "$42,405,248",
     "publicinstitution": "Royal Free and Unversity College Medical/Univeristy of Toronto"
   },
   {
     "drugid": 18,
     "genericname": "Ingenol Mebutate",
     "brandname": "Picato",
     "companyname": "Leo Labs",
     "indication": "Cancer",
     "price": "$1,108.37",
     "medicared": "$17,225,208",
     "medicareb": "",
     "medicaid": "$249,426",
     "federal": "$17,474,634",
     "publicinstitution": "NCl/University of Queensland"
   },
   {
     "drugid": 19,
     "genericname": "Ivacaftor",
     "brandname": "Kalydeco",
     "companyname": "Vertex",
     "indication": "CF",
     "price": "$23,896.13",
     "medicared": "$57,632,960",
     "medicareb": "",
     "medicaid": "$144,167,684",
     "federal": "$201,800,644",
     "publicinstitution": "Cystic Fibrosis Foundation Therapeutics "
   },
   {
     "drugid": 20,
     "genericname": "Lucinactant",
     "brandname": "SURFAXIN",
     "companyname": "Windtree",
     "indication": "",
     "price": "$860",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Scripps Research Institute "
   },
   {
     "drugid": 21,
     "genericname": "Florbetapir",
     "brandname": "Amyvid",
     "companyname": "Avid Radio",
     "indication": "",
     "price": "$2,857.40",
     "medicared": "",
     "medicareb": "",
     "medicaid": "$33,107,693",
     "federal": "$33,107,693",
     "publicinstitution": "University of Pennsylvannia "
   },
   {
     "drugid": 22,
     "genericname": "Cobicistat, elvitegravir, emtricitabine, tenofovier, disoproxil fumarate",
     "brandname": "Tybost",
     "companyname": "Gilead",
     "indication": "HIV",
     "price": "$241.73",
     "medicared": "",
     "medicareb": "",
     "medicaid": "$134,394",
     "federal": "$134,394",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 23,
     "genericname": "Enzalutamide",
     "brandname": "Xtandi",
     "companyname": "Astellas",
     "indication": "Cancer",
     "price": "$11,918.16",
     "medicared": "$1,182,615,333",
     "medicareb": "",
     "medicaid": "$52,101,826",
     "federal": "$1,234,717,159",
     "publicinstitution": "University of California "
   },
   {
     "drugid": 24,
     "genericname": "Choline",
     "brandname": "",
     "companyname": "MCPRF",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Mayo Clinic"
   },
   {
     "drugid": 25,
     "genericname": "Teduglutide Recombinant ",
     "brandname": "Juxtapid",
     "companyname": "NPS Pharms",
     "indication": "Chlolestrol ",
     "price": "$44,713.53",
     "medicared": "$9,140,587",
     "medicareb": "",
     "medicaid": "$4,617,896",
     "federal": "$13,758,483",
     "publicinstitution": "Toronto General Hospital, University of Toronto "
   },
   {
     "drugid": 26,
     "genericname": "Lomatapide Mesylate",
     "brandname": "Juxtapid",
     "companyname": "Aegerion",
     "indication": "Chlolestrol ",
     "price": "$44,713.53",
     "medicared": "$9,140,587",
     "medicareb": "",
     "medicaid": "$4,617,896",
     "federal": "$13,758,483",
     "publicinstitution": "University of Pennsylvannia "
   },
   {
     "drugid": 27,
     "genericname": "Alogliptin Benzoate",
     "brandname": "",
     "companyname": "Takeda",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Univeristy of Toronto/Tufts College/NE Medical Center"
   },
   {
     "drugid": 28,
     "genericname": "Technetium 99mTc Tilmanocept",
     "brandname": "Lymphoseek",
     "companyname": "Cardinal",
     "indication": "Mapping Agent",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of california- San Diego"
   },
   {
     "drugid": 29,
     "genericname": "Flutemetamol",
     "brandname": "Vizamyl",
     "companyname": "GE",
     "indication": "Brain Imagery ",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of Pittsburgh"
   },
   {
     "drugid": 30,
     "genericname": "Miltefosine",
     "brandname": "Impavido",
     "companyname": "Knight",
     "indication": "Visceral leishmaniasis",
     "price": "",
     "medicared": "$640,215",
     "medicareb": "",
     "medicaid": "",
     "federal": "$640,215",
     "publicinstitution": "Max Plank Institute "
   },
   {
     "drugid": 31,
     "genericname": "Florbetaben",
     "brandname": "Neuraceq",
     "companyname": "Piramal",
     "indication": "Brain Imagery ",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of Pennsylvannia "
   },
   {
     "drugid": 32,
     "genericname": "Eliglustat Tartare",
     "brandname": "Cerdelga",
     "companyname": "Genzyme",
     "indication": "Gaucher disease type 1",
     "price": "$27,300",
     "medicared": "$17,945,890",
     "medicareb": "",
     "medicaid": "$5,660,228",
     "federal": "$23,606,118",
     "publicinstitution": "University of Michigan "
   },
   {
     "drugid": 33,
     "genericname": "Olaparib",
     "brandname": "Lynparza",
     "companyname": "Astrazeneca",
     "indication": "Cancer",
     "price": "$7,082.79",
     "medicared": "$119,106,528",
     "medicareb": "",
     "medicaid": "$26,861,000",
     "federal": "$145,967,528",
     "publicinstitution": "University of Sheffield/Yorkshire Cancer Research/Institute of Cancer Research/University of Cambridge "
   },
   {
     "drugid": 34,
     "genericname": "Peramivir",
     "brandname": "Rapivab",
     "companyname": "Biocryst",
     "indication": "Flu",
     "price": "$316.67",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of Alabama-Birmingham"
   },
   {
     "drugid": 35,
     "genericname": "Deoxycholic Acid",
     "brandname": "Kybella",
     "companyname": "Kythera",
     "indication": "Convexity/Fullness",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of California- Los Angeles"
   },
   {
     "drugid": 36,
     "genericname": "Ivacaftor, lumacaftor",
     "brandname": "Orkambi",
     "companyname": "Vertex",
     "indication": "CF",
     "price": "$20,919.23",
     "medicared": "$48,653,400",
     "medicareb": "",
     "medicaid": "$282,545,276",
     "federal": "$331,198,676",
     "publicinstitution": "Cystic Fibrosis Foundation Therapeutics "
   },
   {
     "drugid": 37,
     "genericname": "Trabectedin ",
     "brandname": "YONDELIS",
     "companyname": "Janssen",
     "indication": "Liposarcoma",
     "price": "$3,036.55",
     "medicared": "$179,131",
     "medicareb": "$9,270,720",
     "medicaid": "$1,313,302",
     "federal": "$10,763,153",
     "publicinstitution": "University of Illinois"
   },
   {
     "drugid": 38,
     "genericname": "Cobicistat, elvitegravir, emtricitabine, tenofovier alafenamide fumarate",
     "brandname": "Genvoya",
     "companyname": "Gilead",
     "indication": "HIV",
     "price": "$3,238.31",
     "medicared": "$871,858,538",
     "medicareb": "",
     "medicaid": "$911,876,985",
     "federal": "$1,783,735,523",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 39,
     "genericname": "Venetoclax",
     "brandname": "Venclexta",
     "companyname": "Abbvie",
     "indication": "Cancer",
     "price": "$1,536.60",
     "medicared": "",
     "medicareb": "",
     "medicaid": "$6,432,529",
     "federal": "$6,432,529",
     "publicinstitution": "Walter and Eliza Hall Institute of Medical Research"
   },
   {
     "drugid": 40,
     "genericname": "Fluciclovine",
     "brandname": "Axumin",
     "companyname": "Blue Earth",
     "indication": "Cancer",
     "price": "$4,005",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 41,
     "genericname": "Obeticholic Acid",
     "brandname": "Ocaliva",
     "companyname": "Intercept",
     "indication": "Biliary Cholangitis",
     "price": "$6,909.83",
     "medicared": "$52,445,398",
     "medicareb": "",
     "medicaid": "$9,197,508",
     "federal": "$61,642,906",
     "publicinstitution": "University of Perugia"
   },
   {
     "drugid": 42,
     "genericname": "Eteplirsen",
     "brandname": "Exondys 51",
     "companyname": "Sarepta",
     "indication": "DMD",
     "price": "$1,600",
     "medicared": "$11,489,143",
     "medicareb": "",
     "medicaid": "$102,230,228",
     "federal": "$113,719,371",
     "publicinstitution": "Leiden Univeristy Medical Center/University of Western Australia"
   },
   {
     "drugid": 43,
     "genericname": "Rucaparib Camsylate",
     "brandname": "",
     "companyname": "Clovis",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Newcastle University/Cancer Research UK"
   },
   {
     "drugid": 44,
     "genericname": "Nusinersen Sodium",
     "brandname": "",
     "companyname": "Biogen",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "University of Massachusets/Cold Spring Harbor Laboratory "
   },
   {
     "drugid": 45,
     "genericname": "Midostaurin ",
     "brandname": "Rydapt",
     "companyname": "Novartis",
     "indication": "Cancer",
     "price": "$4,484",
     "medicared": "$24,792,988",
     "medicareb": "",
     "medicaid": "$10,059,036",
     "federal": "$34,852,024",
     "publicinstitution": "Dana Farber Cancer Institute "
   },
   {
     "drugid": 46,
     "genericname": "Benznidazole",
     "brandname": "Rochagan",
     "companyname": "Chempo research",
     "indication": "Chagas Disease",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Brazilian government, Drugs for Neglected Diseases Initiative Laboratory "
   },
   {
     "drugid": 47,
     "genericname": "Netarsudil Dimesylate",
     "brandname": "RHOPRESSA",
     "companyname": "Aerie",
     "indication": "Glaucoma ",
     "price": "$272.02",
     "medicared": "$15,644,629",
     "medicareb": "",
     "medicaid": "$685,727",
     "federal": "$16,330,356",
     "publicinstitution": "Duke University "
   },
   {
     "drugid": 48,
     "genericname": "Angiotensin II Acetate",
     "brandname": "",
     "companyname": "La Jolla",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "George Washington University "
   },
   {
     "drugid": 49,
     "genericname": "Etravirine",
     "brandname": "Intelence",
     "companyname": "Janssen",
     "indication": "HIV",
     "price": "$1,383.82",
     "medicared": "$93,074,163",
     "medicareb": "",
     "medicaid": "$27,026,452",
     "federal": "$120,100,615",
     "publicinstitution": "Rega Institute "
   },
   {
     "drugid": 50,
     "genericname": "Ioflupane",
     "brandname": "DaTscan",
     "companyname": "GE",
     "indication": "Brain Imagery ",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Northeastern University"
   },
   {
     "drugid": 51,
     "genericname": "Rilpivirine Hydrochloride",
     "brandname": "Edurant",
     "companyname": "Janssen",
     "indication": "HIV",
     "price": "$1,165.29",
     "medicared": "$34,950,354",
     "medicareb": "",
     "medicaid": "$15,940,079",
     "federal": "$50,890,433",
     "publicinstitution": "Rega Institute"
   },
   {
     "drugid": 52,
     "genericname": "Vemurafenib",
     "brandname": "Zelboraf",
     "companyname": "Hoffmann- La Roche",
     "indication": "Cancer",
     "price": "$10,127.42",
     "medicared": "$15,774,166",
     "medicareb": "",
     "medicaid": "$5,001,330",
     "federal": "$20,775,496",
     "publicinstitution": "Yale University/University of California-Berkeley"
   },
   {
     "drugid": 53,
     "genericname": "Carfilzomb",
     "brandname": "Kyprolis",
     "companyname": "Onyx",
     "indication": "Cancer",
     "price": "$1,217.71",
     "medicared": "$5,819,243",
     "medicareb": "$248,150,983",
     "medicaid": "",
     "federal": "$253,970,226",
     "publicinstitution": "Yale University/California Institute of Technology"
   },
   {
     "drugid": 54,
     "genericname": "Linaclotide",
     "brandname": "Linzess",
     "companyname": "Allergan",
     "indication": "Irritable Bowel Syndrome ",
     "price": "$445.02",
     "medicared": "$761,658,895",
     "medicareb": "",
     "medicaid": "$125,025,579",
     "federal": "$886,684,474",
     "publicinstitution": "Whitehead Institute "
   },
   {
     "drugid": 55,
     "genericname": "Radium 223Ra Dichloride",
     "brandname": "Xofigo",
     "companyname": "Bayer",
     "indication": "Cancer",
     "price": "$24,626.30",
     "medicared": "",
     "medicareb": "",
     "medicaid": "$2,154,405",
     "federal": "$2,154,405",
     "publicinstitution": "Norwegian Radium Hospital/University of Oslo"
   },
   {
     "drugid": 56,
     "genericname": "Sofosbuvir",
     "brandname": "Sovaldi",
     "companyname": "Gilead",
     "indication": "HIV",
     "price": "$28,000",
     "medicared": "$11,072,486",
     "medicareb": "",
     "medicaid": "$2,759,295",
     "federal": "$13,831,781",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 57,
     "genericname": "Tavaborole",
     "brandname": "Kerydin",
     "companyname": "Anacor",
     "indication": "onychomycosis",
     "price": "$1,510.85",
     "medicared": "$9,670,613",
     "medicareb": "",
     "medicaid": "$744,868",
     "federal": "$10,415,481",
     "publicinstitution": "Stanford University/ Pennsylvannia State University "
   },
   {
     "drugid": 58,
     "genericname": "Ledipasvirt, sofosbuvir",
     "brandname": "Harvoni",
     "companyname": "Gilead",
     "indication": "Hep C",
     "price": "$31,500",
     "medicared": "$1,726,263,039",
     "medicareb": "",
     "medicaid": "$312,969,804",
     "federal": "$2,039,232,843",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 59,
     "genericname": "Sofosbuvir, velpatasvirt",
     "brandname": "Epclusa",
     "companyname": "Gilead",
     "indication": "Hep C",
     "price": "$24,920",
     "medicared": "$896,454,303",
     "medicareb": "",
     "medicaid": "$492,571,226",
     "federal": "$1,389,025,529",
     "publicinstitution": "Emory University "
   },
   {
     "drugid": 60,
     "genericname": "Ribociclib succinate",
     "brandname": "Kisqali",
     "companyname": "Novartis",
     "indication": "Cancer",
     "price": "$5,297.34",
     "medicared": "$56,743,156",
     "medicareb": "",
     "medicaid": "$16,233,407",
     "federal": "$72,976,563",
     "publicinstitution": "University of Cambridge"
   },
   {
     "drugid": 61,
     "genericname": "Delafloxacin meglumine",
     "brandname": "",
     "companyname": "Melinta",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Yale Univeristy"
   },
   {
     "drugid": 62,
     "genericname": "Sofosbuvir, velpatasvir,voxilaprevirt",
     "brandname": "",
     "companyname": "Gilead",
     "indication": "",
     "price": "",
     "medicared": "",
     "medicareb": "",
     "medicaid": "",
     "federal": "$0",
     "publicinstitution": "Emory University "
   }
  ];


export default drugs;