const drugs = [
   {
     "drugId": 1,
     "genericName": "Bendamustine Hydrochloride",
     "brandName": "Bendeka",
     "companyName": "Cephalon",
     "indication": "Cancer",
     "price": "$2,473.80",
     "medicareD": "$2,102,477",
     "medicareB": "$233,169,546",
     "medicaid": "$22,573,710",
     "federal": "$257,845,733",
     "publicInstitution": "Institute for Microbiology and Experimental Therapy"
   },
   {
     "drugId": 2,
     "genericName": "Methylnaltrexone Bromide",
     "brandName": "RELISTOR",
     "companyName": "Salix",
     "indication": "Irritable Bowel Syndrome",
     "price": "$124.66",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "$11,255,296",
     "federal": "$11,255,296",
     "publicInstitution": "University of Chicago"
   },
   {
     "drugId": 3,
     "genericName": "Gadoxetate Disodium",
     "brandName": "Eovist",
     "companyName": "Bayer",
     "indication": "",
     "price": "$141.96",
     "medicareD": "",
     "medicareB": "$985,022",
     "medicaid": "$132,577",
     "federal": "$1,117,599",
     "publicInstitution": "Massachusets General Hospital "
   },
   {
     "drugId": 4,
     "genericName": "Lobenguane Sulfate",
     "brandName": "",
     "companyName": "GE",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of Michigan "
   },
   {
     "drugId": 5,
     "genericName": "Lacosamide",
     "brandName": "Vimpat",
     "companyName": "UCB",
     "indication": "Seizures",
     "price": "$943.11",
     "medicareD": "$545,362,956",
     "medicareB": "",
     "medicaid": "$356,847,175",
     "federal": "$902,210,131",
     "publicInstitution": "Univeristy of Houston/Research Corporation Tech"
   },
   {
     "drugId": 6,
     "genericName": "Plerixafor",
     "brandName": "Mozobil",
     "companyName": "Genzyme",
     "indication": "",
     "price": "$8,425.76",
     "medicareD": "$4,422,846",
     "medicareB": "$19,707,513",
     "medicaid": "$4,030,405",
     "federal": "$28,160,764",
     "publicInstitution": "Rega Institute for Medical Research"
   },
   {
     "drugId": 7,
     "genericName": "Gadofosveset Trisodium",
     "brandName": "Vasovist",
     "companyName": "Lantheus ",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Massachusetts General Hospital "
   },
   {
     "drugId": 8,
     "genericName": "Artemether, lumefantrine",
     "brandName": "Coartem",
     "companyName": "Novartis",
     "indication": "Malaria",
     "price": "$122.63",
     "medicareD": "$97,342",
     "medicareB": "",
     "medicaid": "$28,270",
     "federal": "$125,612",
     "publicInstitution": "Institute of Microbiology and Epidemology "
   },
   {
     "drugId": 9,
     "genericName": "Pralatrexate",
     "brandName": "Folotyn",
     "companyName": "Allos",
     "indication": "Cancer",
     "price": "$5,770.87",
     "medicareD": "$981,871",
     "medicareB": "$17,107,437",
     "medicaid": "$866,871",
     "federal": "$18,956,179",
     "publicInstitution": "Sloan-Kettering for Cancer Research, SRI International"
   },
   {
     "drugId": 10,
     "genericName": "Romidepsin",
     "brandName": "Istodax",
     "companyName": "Celgene",
     "indication": "Cancer",
     "price": "$3,198.65",
     "medicareD": "$506,966",
     "medicareB": "$32,077,997",
     "medicaid": "$2,928,845",
     "federal": "$35,513,808",
     "publicInstitution": "Harvard Univeristy/University of Tokyo"
   },
   {
     "drugId": 11,
     "genericName": "Capsaicin",
     "brandName": "",
     "companyName": "Acorda",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of California "
   },
   {
     "drugId": 12,
     "genericName": "Fampridine",
     "brandName": "Ampyra",
     "companyName": "Acorda",
     "indication": "MS",
     "price": "$2,934.14",
     "medicareD": "$282,304,089",
     "medicareB": "",
     "medicaid": "",
     "federal": "$282,304,089",
     "publicInstitution": "Purdue University "
   },
   {
     "drugId": 13,
     "genericName": "Ulipristal Acetate",
     "brandName": "Ella",
     "companyName": "Lab HRA",
     "indication": "",
     "price": "$35.75",
     "medicareD": "$21,367",
     "medicareB": "",
     "medicaid": "$1,160,264",
     "federal": "$1,181,631",
     "publicInstitution": "HHS/Research Triangle Institute "
   },
   {
     "drugId": 14,
     "genericName": "Eribulin Mesylate",
     "brandName": "Halaven",
     "companyName": "Eisai",
     "indication": "Cancer",
     "price": "$1,180",
     "medicareD": "$906,346",
     "medicareB": "$51,908,493",
     "medicaid": "",
     "federal": "$52,814,839",
     "publicInstitution": "Harvard Univeristy/NCl"
   },
   {
     "drugId": 15,
     "genericName": "Abiraterone Acetate",
     "brandName": "Zytiga",
     "companyName": "Janssen",
     "indication": "Cancer",
     "price": "",
     "medicareD": "$1,475,649,551",
     "medicareB": "",
     "medicaid": "$83,846,549",
     "federal": "$1,559,496,100",
     "publicInstitution": "Institute of Cancer Research (UK)/Univeristy of London"
   },
   {
     "drugId": 16,
     "genericName": "Linagliptin",
     "brandName": "Tradjenta",
     "companyName": "Boehringer",
     "indication": "Diabetes",
     "price": "$462.34",
     "medicareD": "$1,043,195,403",
     "medicareB": "",
     "medicaid": "$136,100,254",
     "federal": "$1,179,295,657",
     "publicInstitution": "Univeristy of Toronto/Tufts College/NE Medical Center"
   },
   {
     "drugId": 17,
     "genericName": "Deferiprone",
     "brandName": "Ferriprox",
     "companyName": "Apopharma",
     "indication": "",
     "price": "$6,363.07",
     "medicareD": "$21,276,965",
     "medicareB": "",
     "medicaid": "$21,128,283",
     "federal": "$42,405,248",
     "publicInstitution": "Royal Free and Unversity College Medical/Univeristy of Toronto"
   },
   {
     "drugId": 18,
     "genericName": "Ingenol Mebutate",
     "brandName": "Picato",
     "companyName": "Leo Labs",
     "indication": "Cancer",
     "price": "$1,108.37",
     "medicareD": "$17,225,208",
     "medicareB": "",
     "medicaid": "$249,426",
     "federal": "$17,474,634",
     "publicInstitution": "NCl/University of Queensland"
   },
   {
     "drugId": 19,
     "genericName": "Ivacaftor",
     "brandName": "Kalydeco",
     "companyName": "Vertex",
     "indication": "CF",
     "price": "$23,896.13",
     "medicareD": "$57,632,960",
     "medicareB": "",
     "medicaid": "$144,167,684",
     "federal": "$201,800,644",
     "publicInstitution": "Cystic Fibrosis Foundation Therapeutics "
   },
   {
     "drugId": 20,
     "genericName": "Lucinactant",
     "brandName": "SURFAXIN",
     "companyName": "Windtree",
     "indication": "",
     "price": "$860",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Scripps Research Institute "
   },
   {
     "drugId": 21,
     "genericName": "Florbetapir",
     "brandName": "Amyvid",
     "companyName": "Avid Radio",
     "indication": "",
     "price": "$2,857.40",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "$33,107,693",
     "federal": "$33,107,693",
     "publicInstitution": "University of Pennsylvannia "
   },
   {
     "drugId": 22,
     "genericName": "Cobicistat, elvitegravir, emtricitabine, tenofovier, disoproxil fumarate",
     "brandName": "Tybost",
     "companyName": "Gilead",
     "indication": "HIV",
     "price": "$241.73",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "$134,394",
     "federal": "$134,394",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 23,
     "genericName": "Enzalutamide",
     "brandName": "Xtandi",
     "companyName": "Astellas",
     "indication": "Cancer",
     "price": "$11,918.16",
     "medicareD": "$1,182,615,333",
     "medicareB": "",
     "medicaid": "$52,101,826",
     "federal": "$1,234,717,159",
     "publicInstitution": "University of California "
   },
   {
     "drugId": 24,
     "genericName": "Choline",
     "brandName": "",
     "companyName": "MCPRF",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Mayo Clinic"
   },
   {
     "drugId": 25,
     "genericName": "Teduglutide Recombinant ",
     "brandName": "Juxtapid",
     "companyName": "NPS Pharms",
     "indication": "Chlolestrol ",
     "price": "$44,713.53",
     "medicareD": "$9,140,587",
     "medicareB": "",
     "medicaid": "$4,617,896",
     "federal": "$13,758,483",
     "publicInstitution": "Toronto General Hospital, University of Toronto "
   },
   {
     "drugId": 26,
     "genericName": "Lomatapide Mesylate",
     "brandName": "Juxtapid",
     "companyName": "Aegerion",
     "indication": "Chlolestrol ",
     "price": "$44,713.53",
     "medicareD": "$9,140,587",
     "medicareB": "",
     "medicaid": "$4,617,896",
     "federal": "$13,758,483",
     "publicInstitution": "University of Pennsylvannia "
   },
   {
     "drugId": 27,
     "genericName": "Alogliptin Benzoate",
     "brandName": "",
     "companyName": "Takeda",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Univeristy of Toronto/Tufts College/NE Medical Center"
   },
   {
     "drugId": 28,
     "genericName": "Technetium 99mTc Tilmanocept",
     "brandName": "Lymphoseek",
     "companyName": "Cardinal",
     "indication": "Mapping Agent",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of california- San Diego"
   },
   {
     "drugId": 29,
     "genericName": "Flutemetamol",
     "brandName": "Vizamyl",
     "companyName": "GE",
     "indication": "Brain Imagery ",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of Pittsburgh"
   },
   {
     "drugId": 30,
     "genericName": "Miltefosine",
     "brandName": "Impavido",
     "companyName": "Knight",
     "indication": "Visceral leishmaniasis",
     "price": "",
     "medicareD": "$640,215",
     "medicareB": "",
     "medicaid": "",
     "federal": "$640,215",
     "publicInstitution": "Max Plank Institute "
   },
   {
     "drugId": 31,
     "genericName": "Florbetaben",
     "brandName": "Neuraceq",
     "companyName": "Piramal",
     "indication": "Brain Imagery ",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of Pennsylvannia "
   },
   {
     "drugId": 32,
     "genericName": "Eliglustat Tartare",
     "brandName": "Cerdelga",
     "companyName": "Genzyme",
     "indication": "Gaucher disease type 1",
     "price": "$27,300",
     "medicareD": "$17,945,890",
     "medicareB": "",
     "medicaid": "$5,660,228",
     "federal": "$23,606,118",
     "publicInstitution": "University of Michigan "
   },
   {
     "drugId": 33,
     "genericName": "Olaparib",
     "brandName": "Lynparza",
     "companyName": "Astrazeneca",
     "indication": "Cancer",
     "price": "$7,082.79",
     "medicareD": "$119,106,528",
     "medicareB": "",
     "medicaid": "$26,861,000",
     "federal": "$145,967,528",
     "publicInstitution": "University of Sheffield/Yorkshire Cancer Research/Institute of Cancer Research/University of Cambridge "
   },
   {
     "drugId": 34,
     "genericName": "Peramivir",
     "brandName": "Rapivab",
     "companyName": "Biocryst",
     "indication": "Flu",
     "price": "$316.67",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of Alabama-Birmingham"
   },
   {
     "drugId": 35,
     "genericName": "Deoxycholic Acid",
     "brandName": "Kybella",
     "companyName": "Kythera",
     "indication": "Convexity/Fullness",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of California- Los Angeles"
   },
   {
     "drugId": 36,
     "genericName": "Ivacaftor, lumacaftor",
     "brandName": "Orkambi",
     "companyName": "Vertex",
     "indication": "CF",
     "price": "$20,919.23",
     "medicareD": "$48,653,400",
     "medicareB": "",
     "medicaid": "$282,545,276",
     "federal": "$331,198,676",
     "publicInstitution": "Cystic Fibrosis Foundation Therapeutics "
   },
   {
     "drugId": 37,
     "genericName": "Trabectedin ",
     "brandName": "YONDELIS",
     "companyName": "Janssen",
     "indication": "Liposarcoma",
     "price": "$3,036.55",
     "medicareD": "$179,131",
     "medicareB": "$9,270,720",
     "medicaid": "$1,313,302",
     "federal": "$10,763,153",
     "publicInstitution": "University of Illinois"
   },
   {
     "drugId": 38,
     "genericName": "Cobicistat, elvitegravir, emtricitabine, tenofovier alafenamide fumarate",
     "brandName": "Genvoya",
     "companyName": "Gilead",
     "indication": "HIV",
     "price": "$3,238.31",
     "medicareD": "$871,858,538",
     "medicareB": "",
     "medicaid": "$911,876,985",
     "federal": "$1,783,735,523",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 39,
     "genericName": "Venetoclax",
     "brandName": "Venclexta",
     "companyName": "Abbvie",
     "indication": "Cancer",
     "price": "$1,536.60",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "$6,432,529",
     "federal": "$6,432,529",
     "publicInstitution": "Walter and Eliza Hall Institute of Medical Research"
   },
   {
     "drugId": 40,
     "genericName": "Fluciclovine",
     "brandName": "Axumin",
     "companyName": "Blue Earth",
     "indication": "Cancer",
     "price": "$4,005",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 41,
     "genericName": "Obeticholic Acid",
     "brandName": "Ocaliva",
     "companyName": "Intercept",
     "indication": "Biliary Cholangitis",
     "price": "$6,909.83",
     "medicareD": "$52,445,398",
     "medicareB": "",
     "medicaid": "$9,197,508",
     "federal": "$61,642,906",
     "publicInstitution": "University of Perugia"
   },
   {
     "drugId": 42,
     "genericName": "Eteplirsen",
     "brandName": "Exondys 51",
     "companyName": "Sarepta",
     "indication": "DMD",
     "price": "$1,600",
     "medicareD": "$11,489,143",
     "medicareB": "",
     "medicaid": "$102,230,228",
     "federal": "$113,719,371",
     "publicInstitution": "Leiden Univeristy Medical Center/University of Western Australia"
   },
   {
     "drugId": 43,
     "genericName": "Rucaparib Camsylate",
     "brandName": "",
     "companyName": "Clovis",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Newcastle University/Cancer Research UK"
   },
   {
     "drugId": 44,
     "genericName": "Nusinersen Sodium",
     "brandName": "",
     "companyName": "Biogen",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "University of Massachusets/Cold Spring Harbor Laboratory "
   },
   {
     "drugId": 45,
     "genericName": "Midostaurin ",
     "brandName": "Rydapt",
     "companyName": "Novartis",
     "indication": "Cancer",
     "price": "$4,484",
     "medicareD": "$24,792,988",
     "medicareB": "",
     "medicaid": "$10,059,036",
     "federal": "$34,852,024",
     "publicInstitution": "Dana Farber Cancer Institute "
   },
   {
     "drugId": 46,
     "genericName": "Benznidazole",
     "brandName": "Rochagan",
     "companyName": "Chempo research",
     "indication": "Chagas Disease",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Brazilian government, Drugs for Neglected Diseases Initiative Laboratory "
   },
   {
     "drugId": 47,
     "genericName": "Netarsudil Dimesylate",
     "brandName": "RHOPRESSA",
     "companyName": "Aerie",
     "indication": "Glaucoma ",
     "price": "$272.02",
     "medicareD": "$15,644,629",
     "medicareB": "",
     "medicaid": "$685,727",
     "federal": "$16,330,356",
     "publicInstitution": "Duke University "
   },
   {
     "drugId": 48,
     "genericName": "Angiotensin II Acetate",
     "brandName": "",
     "companyName": "La Jolla",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "George Washington University "
   },
   {
     "drugId": 49,
     "genericName": "Etravirine",
     "brandName": "Intelence",
     "companyName": "Janssen",
     "indication": "HIV",
     "price": "$1,383.82",
     "medicareD": "$93,074,163",
     "medicareB": "",
     "medicaid": "$27,026,452",
     "federal": "$120,100,615",
     "publicInstitution": "Rega Institute "
   },
   {
     "drugId": 50,
     "genericName": "Ioflupane",
     "brandName": "DaTscan",
     "companyName": "GE",
     "indication": "Brain Imagery ",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Northeastern University"
   },
   {
     "drugId": 51,
     "genericName": "Rilpivirine Hydrochloride",
     "brandName": "Edurant",
     "companyName": "Janssen",
     "indication": "HIV",
     "price": "$1,165.29",
     "medicareD": "$34,950,354",
     "medicareB": "",
     "medicaid": "$15,940,079",
     "federal": "$50,890,433",
     "publicInstitution": "Rega Institute"
   },
   {
     "drugId": 52,
     "genericName": "Vemurafenib",
     "brandName": "Zelboraf",
     "companyName": "Hoffmann- La Roche",
     "indication": "Cancer",
     "price": "$10,127.42",
     "medicareD": "$15,774,166",
     "medicareB": "",
     "medicaid": "$5,001,330",
     "federal": "$20,775,496",
     "publicInstitution": "Yale University/University of California-Berkeley"
   },
   {
     "drugId": 53,
     "genericName": "Carfilzomb",
     "brandName": "Kyprolis",
     "companyName": "Onyx",
     "indication": "Cancer",
     "price": "$1,217.71",
     "medicareD": "$5,819,243",
     "medicareB": "$248,150,983",
     "medicaid": "",
     "federal": "$253,970,226",
     "publicInstitution": "Yale University/California Institute of Technology"
   },
   {
     "drugId": 54,
     "genericName": "Linaclotide",
     "brandName": "Linzess",
     "companyName": "Allergan",
     "indication": "Irritable Bowel Syndrome ",
     "price": "$445.02",
     "medicareD": "$761,658,895",
     "medicareB": "",
     "medicaid": "$125,025,579",
     "federal": "$886,684,474",
     "publicInstitution": "Whitehead Institute "
   },
   {
     "drugId": 55,
     "genericName": "Radium 223Ra Dichloride",
     "brandName": "Xofigo",
     "companyName": "Bayer",
     "indication": "Cancer",
     "price": "$24,626.30",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "$2,154,405",
     "federal": "$2,154,405",
     "publicInstitution": "Norwegian Radium Hospital/University of Oslo"
   },
   {
     "drugId": 56,
     "genericName": "Sofosbuvir",
     "brandName": "Sovaldi",
     "companyName": "Gilead",
     "indication": "HIV",
     "price": "$28,000",
     "medicareD": "$11,072,486",
     "medicareB": "",
     "medicaid": "$2,759,295",
     "federal": "$13,831,781",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 57,
     "genericName": "Tavaborole",
     "brandName": "Kerydin",
     "companyName": "Anacor",
     "indication": "onychomycosis",
     "price": "$1,510.85",
     "medicareD": "$9,670,613",
     "medicareB": "",
     "medicaid": "$744,868",
     "federal": "$10,415,481",
     "publicInstitution": "Stanford University/ Pennsylvannia State University "
   },
   {
     "drugId": 58,
     "genericName": "Ledipasvirt, sofosbuvir",
     "brandName": "Harvoni",
     "companyName": "Gilead",
     "indication": "Hep C",
     "price": "$31,500",
     "medicareD": "$1,726,263,039",
     "medicareB": "",
     "medicaid": "$312,969,804",
     "federal": "$2,039,232,843",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 59,
     "genericName": "Sofosbuvir, velpatasvirt",
     "brandName": "Epclusa",
     "companyName": "Gilead",
     "indication": "Hep C",
     "price": "$24,920",
     "medicareD": "$896,454,303",
     "medicareB": "",
     "medicaid": "$492,571,226",
     "federal": "$1,389,025,529",
     "publicInstitution": "Emory University "
   },
   {
     "drugId": 60,
     "genericName": "Ribociclib succinate",
     "brandName": "Kisqali",
     "companyName": "Novartis",
     "indication": "Cancer",
     "price": "$5,297.34",
     "medicareD": "$56,743,156",
     "medicareB": "",
     "medicaid": "$16,233,407",
     "federal": "$72,976,563",
     "publicInstitution": "University of Cambridge"
   },
   {
     "drugId": 61,
     "genericName": "Delafloxacin meglumine",
     "brandName": "",
     "companyName": "Melinta",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Yale Univeristy"
   },
   {
     "drugId": 62,
     "genericName": "Sofosbuvir, velpatasvir,voxilaprevirt",
     "brandName": "",
     "companyName": "Gilead",
     "indication": "",
     "price": "",
     "medicareD": "",
     "medicareB": "",
     "medicaid": "",
     "federal": "$0",
     "publicInstitution": "Emory University "
   }
  ];


export default drugs;