const shows = require('./shows/shows.service.js');
const users = require('./users/users.service.js');
const showComments = require('./show_comments/show_comments.service.js');
const uploads = require('./uploads/uploads.service.js');
const tags = require('./tags/tags.service.js');
const showsTags = require('./shows_tags/shows_tags.service.js');
const events = require('./events/events.service.js');
const tldrs = require('./tldrs/tldrs.service.js');
const tldrVersions = require('./tldr_versions/tldr_versions.service.js');
const categories = require('./categories/categories.service.js');
const mailer = require('./mailer/mailer.service.js');
const authmanagement = require('./authmanagement/authmanagement.service.js');
const usersSavedtldrs = require('./users_savedtldrs/users_savedtldrs.service.js');
const tldrsVotes = require('./tldrs_votes/tldrs_votes.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(shows);
  app.configure(users);
  app.configure(showComments);
  app.configure(uploads);
  app.configure(tags);
  app.configure(showsTags);
  app.configure(events);
  app.configure(tldrs);
  app.configure(tldrVersions);
  app.configure(categories);
  app.configure(mailer);
  app.configure(authmanagement);
  app.configure(usersSavedtldrs);
  app.configure(tldrsVotes);
};
